[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ExpressionData = "479be80e-0d6f-4501-bee0-9ae8a09d31d3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
BenchmarkTools = "1"
DataFrames = "1"
julia = "1.6"
