name = "ExpressionData"
uuid = "479be80e-0d6f-4501-bee0-9ae8a09d31d3"
authors = ["Chris Damour"]
version = "1.1.8"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
Arrow = "2"
DataFrames = "1"
HDF5 = "0.16, 0.17"
JLD2 = "0.4, 0.5"
julia = "1.6.7"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames", "Test"]
